import PDFDocument from 'pdfkit';

/**
 * Generates a professional PDF interview feedback report.
 * @param {object} params
 * @param {string} params.candidateName
 * @param {object} params.session - interview session record
 * @param {Array<{question, expected_answer, answer_text, topic}>} params.qaPairs
 * @param {object} params.feedback - AI feedback result
 * @returns {Promise<Buffer>}
 */
export const generateFeedbackPDF = ({ candidateName, session, qaPairs, feedback }) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // ---------- Header ----------
      doc
        .fontSize(22)
        .fillColor('#4F46E5')
        .text('InterviewAce AI', { align: 'left' })
        .fontSize(14)
        .fillColor('#111827')
        .text('Mock Interview Feedback Report', { align: 'left' })
        .moveDown(0.5);

      doc
        .fontSize(10)
        .fillColor('#6B7280')
        .text(`Candidate: ${candidateName}`)
        .text(`Role: ${formatLabel(session.role)}`)
        .text(`Difficulty: ${formatLabel(session.difficulty)}`)
        .text(`Interview Date: ${new Date(session.started_at).toLocaleString()}`)
        .moveDown(1);

      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke().moveDown(1);

      // ---------- Scores ----------
      doc.fontSize(14).fillColor('#111827').text('Performance Scores', { underline: true }).moveDown(0.5);

      const scoreRows = [
        ['Overall Score', feedback.overall_score],
        ['Technical Score', feedback.technical_score],
        ['Communication Score', feedback.communication_score],
        ['Clarity Score', feedback.clarity_score],
        ['Confidence Score', feedback.confidence_score],
      ];

      scoreRows.forEach(([label, value]) => {
        doc
          .fontSize(11)
          .fillColor('#374151')
          .text(`${label}: `, { continued: true })
          .fillColor('#4F46E5')
          .text(`${value}/100`);
      });

      doc.moveDown(1);

      // ---------- Improvement Suggestions ----------
      doc.fontSize(14).fillColor('#111827').text('Improvement Suggestions', { underline: true }).moveDown(0.5);

      (feedback.improvement_suggestions || []).forEach((s, i) => {
        doc.fontSize(10).fillColor('#374151').text(`${i + 1}. ${s}`, { indent: 10 });
      });

      doc.moveDown(1);

      // ---------- Questions & Answers ----------
      doc.fontSize(14).fillColor('#111827').text('Questions & Answers', { underline: true }).moveDown(0.5);

      qaPairs.forEach((qa, i) => {
        if (doc.y > 680) doc.addPage();

        doc.fontSize(11).fillColor('#111827').text(`Q${i + 1}. ${qa.question}`, { width: 495 });
        doc
          .fontSize(9)
          .fillColor('#6B7280')
          .text(`Topic: ${qa.topic || 'General'}`, { width: 495 })
          .moveDown(0.2);
        doc
          .fontSize(10)
          .fillColor('#374151')
          .text(`Your Answer: ${qa.answer_text || '(No answer provided)'}`, { width: 495 })
          .moveDown(0.8);
      });

      // ---------- Sample Answers ----------
      if (feedback.better_sample_answers?.length) {
        if (doc.y > 650) doc.addPage();
        doc.fontSize(14).fillColor('#111827').text('Suggested Sample Answers', { underline: true }).moveDown(0.5);

        feedback.better_sample_answers.forEach((s) => {
          if (doc.y > 680) doc.addPage();
          doc.fontSize(10).fillColor('#111827').text(`Q: ${s.question}`, { width: 495 }).moveDown(0.2);
          doc.fontSize(10).fillColor('#374151').text(`Sample Answer: ${s.sample_answer}`, { width: 495 }).moveDown(0.8);
        });
      }

      // ---------- Footer ----------
      doc
        .moveDown(2)
        .fontSize(8)
        .fillColor('#9CA3AF')
        .text('Generated by InterviewAce AI - This report is AI-generated and intended for practice purposes.', {
          align: 'center',
        });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

const formatLabel = (value = '') =>
  value
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
